name: Build and Push OACAfront Docker Image

on:
  push:
    branches: [main, master] # Déclenche le workflow sur les push vers main ou master
  pull_request:
    branches: [main, master] # Déclenche le workflow sur les pull requests vers main ou master

env:
  IMAGE_NAME: hammoudihayfa/oaca-front:latest # Nom de l'image Docker sur Docker Hub

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Utilise un runner Linux hébergé par GitHub (gratuit pour les dépôts publics)

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 # Récupère le code de votre dépôt

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2 # Configure Docker Buildx pour des builds optimisés

    - name: Login to Docker Hub
      uses: docker/login-action@v2 # Action pour se connecter à Docker Hub
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }} 
        password: ${{ secrets.DOCKERHUB_TOKEN }}   

    - name: Build and push Docker image
      run: |
        echo "Building Docker image: $IMAGE_NAME"
        # Construit l'image Docker en utilisant le Dockerfile dans le répertoire courant
        docker build -t $IMAGE_NAME .
        echo "Pushing Docker image to Docker Hub: $IMAGE_NAME"
        # Pousse l'image construite vers Docker Hub
        docker push $IMAGE_NAME
        echo "Docker image pushed successfully!"
